export { default as Main } from './Main'
export { default as Welcome } from './Welcome'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Social } from './Social'
