export { default as Main } from './Main'
export { default as Welcome } from './Welcome'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Social } from './Social'
export { default as Personal } from './Personal'
export { default as Notification } from './Notification'
export { default as UserProfile } from './UserProfile'
